Fixed keeping refs to class 'House' breaking init of unrelated classes
CFToolsGameLabs/game-plugin-dayz pull request #9
Opened 2021-05-26 21:06 UTC by lava76

This also fixes Expansion "simple territory" flag placing

2021-05-26 21:27 UTC, FlorianSW commented
Tested on a local setup that I used to reproduce the territory flag issue:
- with the workshop release: create territory action broken
- with the built version of this PR: create territory action available

2021-05-27 12:59 UTC, philippj requested changes

2021-05-27 12:59 UTC, philippj commented on Scripts/3_Game/classes.c
> +    Object Ref() { return GetGame().GetObjectByNetworkId(id_low, id_high); }
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/3_Game/classes.c
> +        Object _reference = Ref();
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/4_World/4_Hooking/!CarScript.c
> +        _registeredInstance = new _Vehicle(this);
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/4_World/4_Hooking/!DayZAnimal.c
> +        _registeredInstance = new _AI(this, false);
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/4_World/4_Hooking/!DayZInfected.c
> +        _registeredInstance = new _AI(this, true);
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/4_World/4_Hooking/!HeliCrash.c
> +        _registeredInstance = new _Event(this.GetType(), "helicopter", this);
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/4_World/4_Hooking/!HeliCrash.c
> +            _registeredInstance = new _Event(this.GetType(), "helicopter", this);
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/4_World/4_Hooking/!PoliceWreck.c
> +        _registeredInstance = new _Event(this.GetType(), "car", this);
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/4_World/4_Hooking/!PoliceWreck.c
> +        _registeredInstance = new _Event(this.GetType(), "car", this);
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/4_World/4_Hooking/!PoliceWreck.c
> +        _registeredInstance = new _Event(this.GetType(), "car", this);
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 12:59 UTC, philippj commented on Scripts/4_World/4_Hooking/!PoliceWreck.c
> +        _registeredInstance = new _Event(this.GetType(), "car", this);
Class attributes shall be accessed via `this.<attribute>`

2021-05-27 15:10 UTC, merged

2021-05-27 15:26 UTC, philippj commented
Reverted in #10 .

`GetObjectByNetworkId` causes a heavy performance impact and is not feasible in production. Also, `GetPosition` on objects returned this way always give `0,0,0`.